---
- name: Install MedShakeEHR on Vagrant VM
  hosts: msehr
  become: true
  vars_files:
    - secrets.yml
  pre_tasks:
    - name: Update APT cache & Upgrade OS
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: dist
  roles:
    - { role: marsante.medshakeehr }

  tasks:
    - name: Sync sources with working directory
      ansible.builtin.copy:
        src: /vagrant/
        dest: "{{ msehr_dir }}"
        remote_src: true
        directory_mode: true
        mode: preserve
      when: stage == "testing"

    - name: Add good permissions and ownership to medshakeehr folder
      ansible.builtin.file:
        path: "{{ msehr_dir }}"
        state: directory
        recurse: true
        owner: www-data
        group: "{{ user }}"
        mode: '0755'
