version: '2'

services:
    web:
        image: medshake-ehr-web:latest
        ports:
            - "80:80"
        volumes:
            - ~/ehr/log:/var/log
        links:
            - db:db
        environment:
            # EHR_* Env Variable passthru
            - EHR_SERVER_NAME=${EHR_SERVER_NAME}
            - EHR_SERVER_ALIAS=${EHR_SERVER_ALIAS}
            - EHR_DBMS_NAME=${EHR_DBMS_NAME}
            - EHR_DBMS_ROOT_PASSWORD=${EHR_DBMS_ROOT_PASSWORD}
            - EHR_DBMS_USER_NAME=${EHR_DBMS_USER_NAME}
            - EHR_DBMS_USER_PASSWORD=${EHR_DBMS_USER_PASSWORD}
            - EHR_DBMS_VAR=${EHR_DBMS_VAR}
            - EHR_FINGERPRINT=${EHR_FINGERPRINT}
    db:
        image: medshake-ehr-db:latest
        volumes:
            - ~/ehr/data:/var/lib/mysql
#        ports:
#            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${EHR_DBMS_ROOT_PASSWORD}
            - MYSQL_DATABASE=${EHR_DBMS_NAME}
            - MYSQL_USER=${EHR_DBMS_USER_NAME}
            - MYSQL_PASSWORD=${EHR_DBMS_USER_PASSWORD}

    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - db:db
