#
# This file is part of MedShakeEHR.
#
# Copyright (c) 2017
# Bertrand Boutillier <b.boutillier@gmail.com>
# http://www.medshake.net
#
# MedShakeEHR is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# MedShakeEHR is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with MedShakeEHR.  If not, see <http://www.gnu.org/licenses/>.
#
#
#######################################
#
# Configuration générale de MedShakeEHR au format yaml
#
# Chaque paramètre peut être surchargé de façon spécifique pour chaque
# utilisateur (voir la zone de configuration)
#
#######################################

#######################################
##  general config
protocol: 'http://'
host: 'ehr.local'
homeDirectory: '/home/EHR/'
webDirectory: '/home/EHR/public_html/'
stockageLocation: '/home/EHR/public_html/stockage/'
workingDirectory: '/home/EHR/public_html/workingDirectory/'
cookieDomain: 'ehr.local'
cookieDuration: 31104000
fingerprint: 'dfsdjh54ezaz5'

#######################################
## sql access
sqlServeur: 'localhost'
sqlBase: 'ehr'
sqlUser: 'user'
sqlPass: 'password'
sqlVarPassword: '4fd45sf78s8'


#######################################
## templates impression

# defaut
templateDefautPage: 'base-page-headAndFoot.html.twig'
# ordonnance
templateOrdoHeadAndFoot: 'base-page-headAndFoot.html.twig'
templateOrdoBody: 'ordonnanceBody.html.twig'
templateOrdoALD: 'ordonnanceALD.html.twig'
# compte rendu
templateCrHeadAndFoot: 'base-page-headAndNoFoot.html.twig'
# courrier et certificat
templateCourrierHeadAndFoot: 'base-page-headAndNoFoot.html.twig'


#######################################
## smtp
smtpFrom: 'user@domain.net'
smtpHost: 'smtp.net'
smtpPort: 587
smtpUsername: 'smtpuserlogin'
smtpPassword: 'smtppassword'

#######################################
## apicrypt

apicryptCheminInbox: '/home/EHR/public_html/inbox/'
apicryptCheminArchivesInbox: '/home/EHR/public_html/inboxArchives/'

apicryptCheminFichierNC: '/home/EHR/public_html/workingDirectory/NC/'
apicryptCheminFichierC: '/home/EHR/public_html/workingDirectory/C/'
apicryptCheminVersClefs: '/home/EHR/apicrypt/'
apicryptCheminVersBinaires: '/home/EHR/apicrypt/bin/'
apicryptUtilisateur: 'prenom.NOM'
apicryptAdresse: 'prenom.NOM@medicalXX.apicrypt.org'
apicryptPopHost: 'pop.intermedic.org'
apicryptPopPort: '110'
apicryptPopUser: 'prenom.NOM'
apicryptPopPass: 'passwordapicrypt'




#######################################
## dicom
dicomHost: '192.168.xxx.xxx'
dicomPrefixIdPatient: '1.100.100'
dicomWorkListDirectory: '/home/EHR/public_html/workingDirectory/'
dicomWorkingDirectory: '/home/EHR/public_html/workingDirectory/'
dicomAutoSendPatient2Echo: 'false'

#######################################
## Twig
templateBaseFolder: 'gynobs'
twig:
    environnement:
      cache: false #'/tmp/templates_cache/'
      autoescape: false
    templatesPath:
        - '/'
        - '/login/'
        - '/rechercher/'
        - '/patient/'
        - '/people/'
        - '/configuration/'
        - '/models4print/'
        - '/logs/'
        - '/compta/'
        - '/inbox/'
        - '/dicom/'
        - '/public/'
