#
# This file is part of MedShakeEHR.
#
# Copyright (c) 2017
# Bertrand Boutillier <b.boutillier@gmail.com>
# http://www.medshake.net
#
# MedShakeEHR is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# MedShakeEHR is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with MedShakeEHR.  If not, see <http://www.gnu.org/licenses/>.
#
#
#######################################
#
# FICHIER EXEMPLE A RENOMMER config.yml
#
# Configuration générale de MedShakeEHR au format yaml
#
# Chaque paramètre peut être surchargé de façon spécifique pour chaque
# utilisateur (voir la zone de configuration)
#
# Les chemins peuvent être définis relativement au chemin d'installation ainsi : '#HOMEPATH#chemin/vers/cible/'
# ou en absolu : '/chemin/vers/cible/'
#######################################

#######################################
##  general config
protocol: 'http://'
host: 'ehr.local'
urlHostSuffixe: ''
webDirectory: '#HOMEPATH#public_html/'
stockageLocation: '#HOMEPATH#stockage/'
backupLocation: '#HOMEPATH#backups/'
workingDirectory: '#HOMEPATH#public_html/workingDirectory/'
cookieDomain: 'ehr.local'
cookieDuration: 31104000
fingerprint: 'dfsdjh54ezaz5'

#######################################
## sql access
sqlServeur: 'localhost'
sqlBase: 'ehr'
sqlUser: 'user'
sqlPass: 'password'
sqlVarPassword: '4fd45sf78s8'

#######################################
## Permettre aux praticiens d'être patients (si false, il faudra leur créer une fiche patient)
PraticienPeutEtrePatient: true

#######################################
## administratif
administratifSecteurHonoraires: 1
administratifPeutAvoirFacturesTypes: 'false'
administratifPeutAvoirPrescriptionsTypes: 'false'
administratifPeutAvoirAgenda: 'false'
administratifPeutAvoirRecettes: 'true'
administratifComptaPeutVoirRecettesDe: ''

#######################################
## templates impression
##
# répertoire par défaut
templatesPdfFolder: '#HOMEPATH#templates/models4print/'

# modèle par defaut
templateDefautPage: 'base-page-headAndFoot.html.twig'
# ordonnance
templateOrdoHeadAndFoot: 'base-page-headAndFoot.html.twig'
templateOrdoBody: 'ordonnanceBody.html.twig'
templateOrdoALD: 'ordonnanceALD.html.twig'
# compte rendu
templateCrHeadAndFoot: 'base-page-headAndNoFoot.html.twig'
# courrier et certificat
templateCourrierHeadAndFoot: 'base-page-headAndNoFoot.html.twig'

#######################################
## smtp
smtpTracking: ''
smtpFrom: 'user@domain.net'
smtpFromName: ''
smtpHost: 'smtp.net'
smtpPort: 587
smtpSecureType: 'tls'
smtpOptions: 'off'
smtpUsername: 'smtpuserlogin'
smtpPassword: 'smtppassword'
smtpDefautSujet: 'Document vous concernant'

#######################################
## apicrypt

apicryptCheminInbox: '#HOMEPATH#public_html/inbox/'
apicryptCheminArchivesInbox: '#HOMEPATH#public_html/inboxArchives/'
apicryptInboxMailForUserID: '0'

apicryptCheminFichierNC: '#HOMEPATH#public_html/workingDirectory/NC/'
apicryptCheminFichierC: '#HOMEPATH#public_html/workingDirectory/C/'
apicryptCheminVersClefs: '#HOMEPATH#apicrypt/'
apicryptCheminVersBinaires: '#HOMEPATH#apicrypt/bin/'
apicryptUtilisateur: 'prenom.NOM'
apicryptAdresse: 'prenom.NOM@medicalXX.apicrypt.org'
apicryptSmtpHost: 'smtp.intermedic.org'
apicryptSmtpPort: '25'
apicryptPopHost: 'pop.intermedic.org'
apicryptPopPort: '110'
apicryptPopUser: 'prenom.NOM'
apicryptPopPass: 'passwordapicrypt'
apicryptDefautSujet: 'Document concernant votre patient'

#######################################
## fax en ligne
faxService: 'ecofaxOVH'
ecofaxMyNumber: '0900000000'
ecofaxPass: 'password'

#######################################
## dicom
dicomHost: '192.168.xxx.xxx'
dicomPrefixIdPatient: '1.100.100'
dicomWorkListDirectory: '#HOMEPATH#public_html/workingDirectory/'
dicomWorkingDirectory: '#HOMEPATH#public_html/workingDirectory/'
dicomAutoSendPatient2Echo: 'false'
dicomDiscoverNewTags: 'true'

#######################################
## PhoneCapture
phonecaptureFingerprint: 'phonecapture'
phonecaptureCookieDuration: 31104000
phonecaptureResolutionWidth: 1920
phonecaptureResolutionHeight: 1080

#######################################
## agenda
agendaService: ''
## si agendaService est actif, alors agendaDistantLink doit être mis à ''
agendaDistantLink: 'http://monagenda.agenda.abc'
agendaDistantPatientsOfTheDay: 'http://monagenda.agenda.abc/patientsOfTheDay.json'
agendaLocalPatientsOfTheDay: 'patientsOfTheDay.json'
agendaNumberForPatientsOfTheDay: 0

#######################################
## Rappels RDV par mail
mailRappelLogCampaignDirectory: '#HOMEPATH#public_html/mailsRappelRdvArchives/'
mailRappelDaysBeforeRDV: '3'

#######################################
## SMS (cf /servicesTiers/sms/ )
smsProvider: ''
smsLogCampaignDirectory: '#HOMEPATH#public_html/smsArchives/'
smsDaysBeforeRDV: '3'
smsCreditsFile: 'creditsSMS.txt'
smsSeuilCreditsAlerte: '150'
smsTpoa: 'Dr ....'

#######################################
## Templates affichage écran
templatesFolder: '#HOMEPATH#templates/'

#######################################
## Twig configuration
twigEnvironnementCache: false #'/tmp/templates_cache/'
twigEnvironnementAutoescape: false

#######################################
## LAP
LapOnOff: off
theriaqueMode: 'WS'
theriaqueWsURL: ''
theriaqueShowMedicHospi: 'non'
theriaqueShowMedicNonComer: 'non'
