protocol: http://
host: www.example.com:80
urlHostSuffixe: ""
webDirectory: /app/MedShakeEHR-base/public_html/
stockageLocation: /app/MedShakeEHR-base/stockage/
backupLocation: /app/MedShakeEHR-base/backups/
workingDirectory: /app/MedShakeEHR-base/public_html/workingDirectory/
cookieDomain: www.example.com
cookieDuration: 31104000
fingerprint: LHE1m3idbr4
sqlServeur: db
sqlBase: medshakeehr
sqlUser: root
sqlPass: D1zIzDaSoundOfC!
sqlVarPassword: WyB87M4TMo
templatesFolder: /app/MedShakeEHR-base/templates/
twigEnvironnementCache: false
twigEnvironnementAutoescape: false
