#
# This file is part of MedShakeEHR.
#
# Copyright (c) 2017
# Bertrand Boutillier <b.boutillier@gmail.com>
# http://www.medshake.net
#
# MedShakeEHR is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# MedShakeEHR is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with MedShakeEHR.  If not, see <http://www.gnu.org/licenses/>.
#
#
#######################################
#
# Routes
#
# Ensemble des routes nécessaires à la bonne résolution des url au format yaml
# (Thanks to AltoRouter <http://altorouter.com/> !)
#
#######################################

root: ['GET', '/', 'index']
userLogIn: ['GET', '/login/', 'login/logIn']
userLogInDo: ['POST', '/login/logInDo/', 'login/logInDo']
userLogOutDo: ['GET', '/login/logOutDo/', 'login/logOutDo']
userLogInFirst: ['GET', '/login/logInFirst/', 'login/logInFirst']
userLogInFirstDo: ['POST', '/login/logInFirstDo/', 'login/logInFirstDo']

#RESTful interface
restGeneral: ['GET|POST|PUT|DELETE', '/rest/[a:m]/', 'rest/rest']

#Ajax general
ajaxGetAutocompleteFormValues: ['GET|POST', '/ajax/[a:m]/[:dataset]/[i:type]?/[:setTypes]?/[:linkedTypes]?/', 'actions/ajax']
ajaxGeneral: ['GET|POST', '/ajax/[a:m]/', 'actions/ajax']

#agenda
agendaAjax: ['GET|POST', '/agenda/[i:userID]/ajax/[a:m]/', 'agenda/actions/agendaAjax']
agenda: ['GET', '/agenda/[i:userID]/', 'agenda/agenda']
agendaPatientsOfTheDay: ['GET', '/agenda/[i:userID]/patientsOfTheDay/', 'agenda/agendaPatientsOfTheDay']

#chercher patients / pros
patientsAjax: ['GET|POST', '/[today|patient|pro:porp]s/ajax/[a:m]/', 'rechercher/actions/patientsAjax']
patients: ['GET', '/[today|patient|pro:porp]s/', 'rechercher/patients']

#créer / éditer patient/pros
peopleAjax: ['GET|POST', '/people/ajax/[a:m]/', 'people/actions/peopleAjax']
peopleActions: ['GET|POST', '/people/actions/[a:m]/', 'people/actions/peopleActions']
peopleRegister: ['GET|POST', '/[patient|pro:porp]/register/', 'people/actions/peopleActions']
peopleNew: ['GET', '/[patient|pro:porp]/create/', 'people/peopleNew']
peopleEdit: ['GET', '/[patient|pro:porp]/edit/[i:patient]/', 'people/peopleEdit']
peopleListDeleted: ['GET', '/people/deleted/', 'people/peopleListDeleted']

# relations
peopleRelations: ['GET|POST', '/patient/relations/[i:patient]/', 'people/peopleRelations']

# pro : voir fiche praticien
proView: ['GET', '/pro/[i:proID]/', 'people/proView']

# lap
lapAjax: ['GET|POST', '/lap/ajax/[a:m]/', 'lap/actions/lapAjax']
lapMonographie: ['GET|POST', '/lap/monographie/[i:spe]/[a:section]?/', 'lap/lapMonographie']
lapMonoAnnexes: ['GET|POST', '/lap/monographie/[sub|doc|ei|eis:mode]/[i:spe]/[i:fiche]?/[i:type]?/', 'lap/lapMonoAnnexes']
lapOutils: ['GET|POST', '/outils/lap/', 'lap/lapOutilsIndex']

#dossier patient
patientAjaxIgnoreEmpty: ['GET|POST', '/patient/ajax/[saveCsForm:m]/[ignoreEmpty:ignoreEmpty]/', 'patient/actions/patientAjax']
patientAjax: ['GET|POST', '/patient/ajax/[a:m]/', 'patient/actions/patientAjax']
patientActions: ['GET|POST', '/patient/actions/[a:m]/[i:patientID]?/[i:objetID]?/', 'patient/actions/patientActions']
patientTabs: ['GET|POST', '/patient/[i:patientID]/tab/[a:tab]/', 'patient/patientTabs']
patient: ['GET', '/patient/[i:patient]/', 'patient/patient']

#dicom
dicomActions: ['GET|POST', '/dicom/actions/[a:m]/', 'dicom/actions/dicomActions']
dcViewPatient: ['GET|POST', '/dicom/[i:patientID]/', 'dicom/viewPatient']
dcViewStudy: ['GET', '/dicom/[i:patientID]/study/[:dcStudyID]/', 'dicom/viewStudy']

#logs
logsActions: ['GET|POST', '/logs/actions/[a:m]/', 'logs/actions/logsActions']
logsAjax: ['GET|POST', '/logs/ajax/[a:m]/', 'logs/actions/logsAjax']
logs: ['GET', '/logs/[i:patient]?/[i:typeID]?/[i:instance]?/', 'logs/logs']
historiquePrint: ['GET', '/logs/historiquePrint/[i:objetID]/', 'logs/historiquePrint']
historiqueMailSend: ['GET', '/logs/historiqueMailSend/[i:objetID]/', 'logs/historiqueMailSend']
historiqueMailSendGeneral: ['GET', '/logs/historiqueGeneralMailSend/[i:user]?/[i:start]?/', 'logs/historiqueMailSendGeneral']
historiqueMailSendToPatient: ['GET', '/logs/historiqueMailSendToPatient/[i:patientID]/', 'logs/historiqueMailSendToPatient']
historiqueRappelsSMS: ['GET|POST', '/logs/historiqueRappelsSMS/[:date]?/', 'logs/historiqueRappelsSMS']
historiqueRappelsMail: ['GET|POST', '/logs/historiqueRappelsMail/[:date]?/', 'logs/historiqueRappelsMail']
logsAgenda: ['GET', '/logs/agenda/[i:agenda]?/[i:event]?/', 'logs/logsAgenda']
historiqueAccesHttp: ['GET', '/logs/accesHttp/', 'logs/historiqueAccesHttp']

#pdf
makePDFCr: ['GET|POST', '/makepdf/[i:patient]/[cr|ordo|ordoLAP:printType]/[i:examen]/[anonyme:anonyme]?/', 'print/pdfMake']
makePDFCourrier: ['GET|POST', '/makepdf/[i:patient]/[courrier:printType]/[i:modele]/[i:examen]?/', 'print/pdfMake']
showPDF: ['GET|POST', '/showpdf/[i:objetID]/', 'print/pdfShow']
duplicataPDF: ['GET|POST', '/duplicata/[i:objetID]/', 'print/pdfDuplicata']
pdfMakeFromHistory: ['GET|POST', '/makepdf/[i:patient]/fromHistory/[i:versionID]/', 'print/pdfMakeFromHistory']

#fichier (extraire vers navigateur)
fichierSendToNav: ['GET|POST', '/fichier/[i:fichierID]/', 'fichier/fichierSendToNav']

#compta
comptaActions: ['POST', '/compta/actions/[a:m]/', 'compta/actions/comptaActions']
comptaAjax: ['POST', '/compta/ajax/[a:m]/', 'compta/actions/comptaAjax']
comptaToday: ['GET|POST', '/compta/aujourdhui/', 'compta/today']
compta: ['GET|POST', '/compta/', 'compta/compta']
comptaMemoTarif: ['GET', '/compta/memo-tarifs/[i:user]?/', 'compta/comptaMemoTarifs']

#inbox
inboxAjax: ['POST', '/inbox/ajax/[a:m]/', 'inbox/actions/inboxAjax']
inboxActions: ['POST|GET', '/inbox/actions/[a:m]/[i:mailID]?/', 'inbox/actions/inboxActions']
inbox: ['GET|POST', '/inbox/', 'inbox/inbox']

#transmissions
transmissionsAjax: ['GET|POST', '/transmissions/ajax/[a:m]/', 'transmissions/actions/transmissionsAjax']
transmissionsIndex: ['GET', '/transmissions/[recues|envoyees:transBox]?/', 'transmissions/transmissionsIndex']
transmissionsTransmission: ['GET', '/transmission/[i:transmission]/', 'transmissions/transmissionsTransmission']

#outils
outilsRouletteObs: ['POST|GET', '/outils/roulette-obstetricale/', 'outils/outilsRouletteObs']

#configuration
configAjax: ['POST', '/configuration/ajax/[a:m]/', 'configuration/actions/configAjax']
configActions: ['POST|GET', '/configuration/actions/[a:m]/', 'configuration/actions/configActions']
configIndex: ['GET', '/configuration/', 'configuration/configIndex']
configDataType: ['GET', '/configuration/data-type/[a:groupe]/[i:cat]?/', 'configuration/configDataType']
configDataTypeValues: ['GET', '/configuration/data-type/[a:groupe]/[i:cat]/[i:typeID]/', 'configuration/configDataTypeValues']
configDataCat: ['GET', '/configuration/data-cat/[a:groupe]/', 'configuration/configDataCat']
configPrescriptions: ['GET', '/configuration/prescriptions/[i:user]?/[i:cat]?/', 'configuration/configPrescriptions']
configPrescriptionsCat: ['GET', '/configuration/prescriptions-cat/', 'configuration/configPrescriptionsCat']
configActes: ['GET', '/configuration/actes/[i:user]?/[i:cat]?/', 'configuration/configActes']
configActesCat: ['GET', '/configuration/actes-cat/', 'configuration/configActesCat']
configActesBase: ['GET', '/configuration/actes-base/', 'configuration/configActesBase']
configActesFsePyx: ['GET', '/configuration/actes-fsepyx/[i:id]/', 'configuration/configActesFsePyx']
configDicomTags: ['GET', '/configuration/tags-dicom/', 'configuration/configDicomTags']
configLicence: ['GET', '/configuration/licence/', 'configuration/configLicence']
configCredits: ['GET', '/configuration/credits/', 'configuration/configCredits']

# Configuration Agenda
configAgenda: ['GET', '/configuration/agenda/[i:userID]?/', 'configuration/configAgenda']

# Configuration Apicrypt clefs
configApicrypt: ['GET', '/configuration/apicrypt-clefs/[i:userID]?/', 'configuration/configApicryptClefs']

# Configuration Templates PDF edit
configTemplatesPDF: ['GET', '/configuration/templates-pdf/[i:userID]?/', 'configuration/configTemplatesPDF']
configTemplatesPDFEdit: ['GET', '/configuration/templates-pdf/edit/[*:fichier]/[i:userID]?/', 'configuration/configTemplatesPDFEdit']

# Configuration forms
configFormsCat: ['GET', '/configuration/forms/cat/', 'configuration/configFormsCat']
configFormEdit: ['GET', '/configuration/forms/edit/[i:form]/', 'configuration/configFormEdit']
configFormPreview: ['GET', '/configuration/forms/preview/[i:form]/', 'configuration/configFormPreview']
configForms: ['GET', '/configuration/forms/[a:groupe]?/', 'configuration/configForms']
configShowTagsForCr: ['GET', '/configuration/configShowTagsForCr/[i:objetID]/', 'configuration/configShowTagsForCr']

# configuration technique
configDefaultParams: ['GET', '/configuration/configuration-globale/', 'configuration/configDefaultParams']
configCheckTech: ['GET', '/configuration/check-directory/', 'configuration/configCheckDirectory']
configCleanSession: ['GET', '/configuration/cleanSession/', 'configuration/configCleanSession']
configExecUpgradeScript: ['GET', '/configuration/exec/[a:module]/[*:script]/', 'configuration/configExecUpgradeScript']

# configuration Users
configUsersList: ['GET', '/configuration/users/', 'configuration/configUsersList']
configSpecificUserParam: ['GET', '/configuration/user-param/[i:userID]/', 'configuration/configSpecificUserParam']

# configuration crons
configCron: ['GET', '/configuration/cron/', 'configuration/configCronJobs']

# configuration apply updates
configUpdates: ['GET', '/configuration/applyUpdates/', 'configuration/configApplyUpdates']

# configuration modules
configModules: ['GET', '/configuration/modules/', 'configuration/configModules']
configExportModuleToSQL: ['GET', '/configuration/modules/export/[a:moduleName]/', 'configuration/configExportModuleToSQL']

# configuration LAP
configLapGetSAMS: ['GET', '/configuration/refreshSams/', 'configuration/configLapGetSAMS']

# User
userAjax: ['POST|GET', '/user/ajax/[a:m]/', 'user/actions/userAjax']
userActions: ['POST|GET', '/user/actions/[a:m]/', 'user/actions/userActions']
userParameters: ['GET', '/user/userParameters/', 'user/userParameters']
userPhoneCaptureAccess: ['GET', '/user/userPhoneCaptureAccess/', 'user/userPhoneCaptureAccess']

#public
publicAjax: ['POST', '/public/ajax/[a:m]/', 'public/actions/publicAjax']
publicSigner: ['GET', '/public/signer/', 'public/signer']
publicSignerMerci: ['GET', '/public/signer/merci/', 'public/signerMerci']

#routes pour le module (! on part de controlers/module/ cette fois !)
moduleAjax: ['POST', '/module/ajax/[a:m]/', 'actions/moduleAjax']
moduleActions: ['POST|GET', '/module/actions/[a:m]/[i:patientID]?/[i:objetID]?/', 'actions/moduleActions']


#routes phonecapture
phonecaptureAjax: ['POST|GET', '/phonecapture/ajax/[a:m]/', 'phonecapture/actions/phonecaptureAjax']
phonecaptureQrCodeLogin: ['GET', '/phonecapture/login/[a:key]/', 'phonecapture/phonecaptureQrCodeLogin']
phonecaptureLogout: ['GET', '/phonecapture/logout/', 'phonecapture/phonecaptureLogout']
phonecapture: ['GET', '/phonecapture/', 'phonecapture/phonecapture']
