-- Mise à jour n° de version
UPDATE `system` SET `value`='v5.12.0' WHERE `name`='base' and `groupe`='module';

INSERT INTO `configuration` (`name`, `level`, `toID`, `module`, `cat`, `type`, `description`, `value`) VALUES ('agendaRefreshDelayEvents', 'default', '0', '', 'Agenda', 'int', 'délai en secondes du rafraîchissement live de l\'agenda - 0 pour jamais', '10');

-- Mise à jour formulaire agenda
UPDATE `forms` SET yamlStructure = 'global:\r\n  noFormTags: true\r\nstructure:\r\n  row1:\r\n    class: \'my-0\'\r\n    col1:\r\n      size: 12\r\n      bloc:                          \r\n        - administrativeGenderCode,nolabel         		#14   Sexe\n  row2:\r\n    class: \'my-0\'\r\n    col1:\r\n      size: 6\r\n      bloc:                          \r\n        - birthname,required,nolabel,class={font-weight-bold},autocomplete,data-acTypeID=lastname:birthname 		#1    Nom de naissance\n    col2:\r\n      size: 6\r\n      bloc:                          \r\n        - lastname,nolabel,class={font-weight-bold},autocomplete,data-acTypeID=lastname:birthname 		#2    Nom d usage\n  row3:\r\n    class: \'my-0\'\r\n    col1:\r\n      size: 12\r\n      bloc:                          \r\n        - firstname,nolabel,class={font-weight-bold},required,autocomplete,data-acTypeID=firstname:othersfirstname:igPrenomFA:igPrenomFB:igPrenomFC 		#3    Prénom\n  row4:\r\n    class: \'my-0\'\r\n    col1:\r\n      size: 6\r\n      bloc:                          \r\n        - birthdate,nolabel,required,class=pick-years 		#8    Date de naissance\n    col2:\r\n      size: 6\r\n      bloc:                          \r\n        - nss,nolabel,class=updatable,plus={<i class=\"far fa-address-card\"></i>} 		#180  Numéro de sécu\n  row5:\r\n    class: \'my-0\'\r\n    col1:\r\n      size: 12\r\n      bloc:                          \r\n        - personalEmail,nolabel,class=updatable    		#4    Email personnelle\n  row6:\r\n    class: \'my-0\'\r\n    col1:\r\n      size: 6\r\n      bloc:                          \r\n        - mobilePhone,nolabel,class=updatable      		#7    Téléphone mobile\n    col2:\r\n      size: 6\r\n      bloc:                          \r\n        - homePhone,nolabel,class=updatable        		#10   Téléphone domicile\n\r\n  row7:\r\n    class: \'my-0\'\r\n    col1:\r\n      size: 4\r\n      bloc: \r\n        - streetNumber,nolabel,class=updatable     		#9    n°\n        - postalCodePerso,nolabel,class=updatable  		#13   Code postal\n    col2:\r\n      size: 8\r\n      bloc: \r\n        - street,nolabel,autocomplete,data-acTypeID=street:rueAdressePro,class=updatable 		#11   Voie\n        - city,nolabel,autocomplete,data-acTypeID=city:villeAdressePro,class=updatable 		#12   Ville\n  row8:\r\n    class: \'my-0\'\r\n    col1:\r\n      size: 12\r\n      bloc:\r\n        - notes,nolabel,rows=2,class=updatable     		#21   Notes' where internalName =  'baseModalNewPatient';

-- sens du tri des mails dans inbox 
INSERT INTO `configuration` (`name`, `level`, `toID`, `module`, `cat`, `type`, `description`, `value`) VALUES ('designInboxMailsSortOrder', 'default', '0', '', 'Ergonomie et design', 'texte', 'sens du tri des mails en colonne latérale : date ascendante (asc) ou descendante (desc) ', 'desc');
