-- Mise à jour n° de version
UPDATE `system` SET `value`='v7.1.2' WHERE `name`='base' and `groupe`='module';

-- data_types
SET @catID = (SELECT data_cat.id FROM data_cat WHERE data_cat.name='reglementItems');
INSERT IGNORE INTO `data_types` (`groupe`, `name`, `placeholder`, `label`, `description`, `validationRules`, `validationErrorMsg`, `formType`, `formValues`, `module`, `cat`, `fromID`, `creationDate`, `durationLife`, `displayOrder`) VALUES
('reglement', 'regleBanqueCheque', 'Banque', 'Nom de la Banque', 'Nom de la Banque du chèque', '', '', 'text', '', 'base', @catID, '1', '2019-01-01 00:00:00', '1576800000', '1'),
('reglement', 'regleNumeroCheque', 'n° de chèque', 'n° de chèque', 'n° de chèque', '', '', 'text', '', 'base', @catID, '1', '2019-01-01 00:00:00', '1576800000', '1');

-- forms
SET @catID = (SELECT forms_cat.id FROM forms_cat WHERE forms_cat.name='systemForm');
INSERT IGNORE INTO `forms` (`module`, `internalName`, `name`, `description`, `dataset`, `groupe`, `formMethod`, `formAction`, `cat`, `type`, `yamlStructure`, `options`, `printModel`, `cda`, `javascript`) VALUES
('base', 'baseReglementLibre', 'Formulaire règlement', 'formulaire pour le règlement d\'honoraires libres', 'data_types', 'reglement', 'post', '/patient/ajax/saveReglementForm/', @catID, 'public', 'structure:\r\n row1:\r\n  col1: \r\n    size: 4\r\n    bloc: \r\n      - regleTarifLibreCejour,readonly,plus={€},class=regleTarifCejour 		#189  Tarif\n  col2: \r\n    size: 4\r\n    bloc: \r\n      - regleModulCejour,plus={€},class=regleDepaCejour 		#183  Modulation\n  col3: \r\n    size: 4\r\n    bloc: \r\n      - regleFacture,readonly,plus={€},class=regleFacture 		#180  Facturé\n row2:\r\n  col1: \r\n    size: 4\r\n    bloc: \r\n      - regleCB,plus={€},class=regleCB           		#175  CB\n  col2: \r\n    size: 4\r\n    bloc: \r\n      - regleCheque,plus={€},class=regleCheque   		#176  Chèque\n  col3: \r\n    size: 4\r\n    bloc: \r\n      - regleEspeces,plus={€},class=regleEspeces 		#179  Espèces\n row3:\r\n  col1:\r\n   size: 4\r\n   bloc: \r\n     - regleNumeroCheque,class=regleNumeroCheque   		#400  n° de chèque\n  col2:\r\n   size: 4\r\n   bloc: \r\n     - regleBanqueCheque,class=regleBanqueCheque,autocomplete 		#401  Nom de la Banque\n  col3: \r\n   size: 4\r\n   bloc: \r\n     - regleIdentiteCheque,class=regleIdentiteCheque 		#182  Informations paiement', '', '', '', ''),
('base', 'baseReglementS1', 'Règlement conventionné S1', 'Formulaire pour le règlement d\'honoraires conventionnés secteur 1', 'data_types', 'reglement', 'post', '/patient/ajax/saveReglementForm/', @catID, 'public', 'structure:\r\n row1:\r\n  col1: \r\n    size: 3\r\n    bloc: \r\n      - regleSituationPatient,class=regleSituationPatient 		#188  Situation du patient\n  col2: \r\n    size: 3\r\n    bloc: \r\n      - regleTarifSSCejour,required,readonly,plus={€},class=regleTarifCejour 		#190  Tarif SS\n  col3: \r\n    size: 3\r\n    bloc: \r\n      - regleDepaCejour,plus={€},class=regleDepaCejour 		#177  Dépassement\n  col4: \r\n    size: 3\r\n    bloc: \r\n      - regleFacture,readonly,plus={€},class=regleFacture 		#180  Facturé\n row2:\r\n  col1: \r\n    size: 3\r\n    bloc: \r\n      - regleCB,plus={€},class=regleCB           		#175  CB\n  col2: \r\n    size: 3\r\n    bloc: \r\n      - regleCheque,plus={€},class=regleCheque   		#176  Chèque\n  col3: \r\n    size: 3\r\n    bloc: \r\n      - regleEspeces,plus={€},class=regleEspeces 		#179  Espèces\n  col4: \r\n    size: 3\r\n    bloc: \r\n      - regleTiersPayeur,plus={€},class=regleTiersPayeur 		#191  Tiers\n row3:\r\n  col1:\r\n   size: 4\r\n   bloc: \r\n     - regleNumeroCheque,class=regleNumeroCheque   		#202  n° de chèque\n  col2:\r\n   size: 4\r\n   bloc: \r\n     - regleBanqueCheque,class=regleBanqueCheque,autocomplete 		#201  Nom de la Banque\n  col3: \r\n   size: 4\r\n   bloc: \r\n     - regleIdentiteCheque,class=regleIdentiteCheque 		#182  Informations paiement', '', '', '', ''),
('base', 'baseReglementS2', 'Règlement conventionné S2', 'Formulaire pour le règlement d\'honoraires conventionnés secteur 2', 'data_types', 'reglement', 'post', '/patient/ajax/saveReglementForm/', @catID, 'public', 'structure:\r\n row1:\r\n  col1: \r\n    size: 3\r\n    bloc: \r\n      - regleSituationPatient,class=regleSituationPatient 		#188  Situation du patient\n  col2: \r\n    size: 3\r\n    bloc: \r\n      - regleTarifSSCejour,required,readonly,plus={€},class=regleTarifCejour 		#190  Tarif SS\n  col3: \r\n    size: 3\r\n    bloc: \r\n      - regleDepaCejour,plus={€},class=regleDepaCejour 		#177  Dépassement\n  col4: \r\n    size: 3\r\n    bloc: \r\n      - regleFacture,readonly,plus={€},class=regleFacture 		#180  Facturé\n row2:\r\n  col1: \r\n    size: 3\r\n    bloc: \r\n      - regleCB,plus={€},class=regleCB           		#175  CB\n  col2: \r\n    size: 3\r\n    bloc: \r\n      - regleCheque,plus={€},class=regleCheque   		#176  Chèque\n  col3: \r\n    size: 3\r\n    bloc: \r\n      - regleEspeces,plus={€},class=regleEspeces 		#179  Espèces\n  col4: \r\n    size: 3\r\n    bloc: \r\n      - regleTiersPayeur,plus={€},class=regleTiersPayeur 		#191  Tiers\n row3:\r\n  col1:\r\n   size: 4\r\n   bloc: \r\n     - regleNumeroCheque,class=regleNumeroCheque   		#202  n° de chèque\n  col2:\r\n   size: 4\r\n   bloc: \r\n     - regleBanqueCheque,class=regleBanqueCheque,autocomplete 		#201  Nom de la Banque\n  col3: \r\n   size: 4\r\n   bloc: \r\n     - regleIdentiteCheque,class=regleIdentiteCheque 		#182  Informations paiement', '', '', '', '')
ON DUPLICATE KEY UPDATE module=values(module), internalName=values(internalName), name=values(name), description=values(description), dataset=values(dataset), groupe=values(groupe), formMethod=values(formMethod), formAction=values(formAction), cat=@catID, type=values(type), yamlStructure=values(yamlStructure), options=values(options), printModel=values(printModel), cda=values(cda), javascript=values(javascript);
